version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: healthbuddy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthbuddy
      MYSQL_USER: healthbuddy
      MYSQL_PASSWORD: healthbuddy123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: healthbuddy-app
    environment:
      DATABASE_URL: mysql://healthbuddy:healthbuddy123@mysql:3306/healthbuddy
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      OAUTH_SERVER_URL: ${OAUTH_SERVER_URL:-https://api.manus.im}
      VITE_OAUTH_PORTAL_URL: ${VITE_OAUTH_PORTAL_URL:-https://oauth.manus.im}
      VITE_APP_ID: ${VITE_APP_ID:-your-app-id}
      VITE_APP_TITLE: ${VITE_APP_TITLE:-HealthBuddy}
      VITE_APP_LOGO: ${VITE_APP_LOGO:-https://your-domain.com/logo.png}
      BUILT_IN_FORGE_API_URL: ${BUILT_IN_FORGE_API_URL:-https://api.manus.im}
      BUILT_IN_FORGE_API_KEY: ${BUILT_IN_FORGE_API_KEY:-your-api-key}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY:-pk_test_}
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:

